[package]
name = "task_wrangler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.50"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strum = "0.27.2"
strum_macros = "0.27.2"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
